{% set name = "types-filelock" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-filelock-{{ version }}.tar.gz
  sha256: 21f179490d1ef30d472664e3fe1b4e02def61a888a3cf7cdf2e5204e00e4383b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/filelock-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for filelock
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
